name: Docker Image CI

on: push

env:
  DOCKER_HUB_USERNAME: bohan
  DOCKER_IMAGE_REPO: bohan/nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login
        run: docker login -u "$DOCKER_HUB_USERNAME" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
      - name: Build base image
        run: docker build base --tag nginx
      - name: Build image
        run: docker build . --tag "$DOCKER_IMAGE_REPO:latest"
      - name: Test
        run: docker run --rm "$DOCKER_IMAGE_REPO:latest" sh -ce "nginx -V; nginx -t"
      - name: Tag
        run: docker tag "$DOCKER_IMAGE_REPO:latest" "$DOCKER_IMAGE_REPO:dev"
      - name: Push
        run: docker push "$DOCKER_IMAGE_REPO:dev"
